services:
  db:
    image: mysql:8.0
    container_name: pet-house-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: pet_house_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  influxdb:
    image: influxdb:2.7
    container_name: pet-house-influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}

  emqx:
    image: emqx/emqx:5.8
    container_name: pet-house-emqx
    restart: always
    ports:
      - "1883:1883"       # MQTT TCP
      - "8083:8083"       # MQTT WebSocket
      - "8883:8883"       # MQTT SSL
      - "18083:18083"     # EMQX Dashboard
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    environment:
      EMQX_NAME: pet-house-emqx
      EMQX_HOST: 127.0.0.1
      EMQX_LISTENERS__TCP__DEFAULT__ACCEPTORS: 8
      EMQX_LISTENERS__TCP__DEFAULT__MAX_CONNECTIONS: 1024000

  app:
    build: .
    container_name: pet-house-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - emqx
      - influxdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pet_house_db?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MQTT_BROKER_URL: tcp://emqx:1883
      MQTT_USERNAME: ${MQTT_USERNAME:}
      MQTT_PASSWORD: ${MQTT_PASSWORD:}
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}

volumes:
  mysql_data:
  emqx_data:
  emqx_log:
  influxdb_data: